### ISSUE TITLE
How to use it with Cemu

### ISSUE THREAD

**Issue by Gmrocks125** [TheScienceElf/Blocks-TI-84#14]
In the readme it's written that you have used Cemu, can you provide instructions for doing that?

**Comment by Axylotl** [comment]
@Gmrocks125 
Honestly, I am glad I am not the only one who is having the same question/issue. I think the way it is designed is almost a tails flash drive (if you get the reference). In other words, it is like the calculator that you download and simply throw the files on there. The application would work as a sort of emulator so you can take footage since that simply is not possible on the calculator. 
I am going to try myself and see what I am able to find. I'll let you know what happens!

**Comment by Axylotl** [comment]
@Gmrocks125 
I FIGURED IT OUT!!!! You are gonna need to give me some time to fully explain the process in word form.

**Comment by Axylotl** [comment]
Ok, so the first thing you want to do is install the [CEmu program](https://github.com/CE-Programming/CEmu/releases) onto your laptop/PC. I am using MacOS so the process might be slightly different. Once you download it make sure you have your TI Connect CE application also ready. Here is a step by step guide on what you want to do:

1. Open your CEmu Application. You will see your proto-calculator/simulated calculator and also an area that says "Send Files to Calc". DO NOT USE THIS FUNCTION. This will crash the application.
2. Go to the top left drop down menu of your screen called "Calculator" and then hit "ROM set up wizard".
3. You will get a pop up page with a few different options, click the option to create a ROM.
4. This will send you to the next page where you need to download the DUMP program. Save it to your computer.
5. You now need to launch your TI Connect CE software and send the DUMP program to your calculator. 
6. Once this is installed, use the Asm catalog option and then using your programs "prgm" click on DUMP.
7. IMPORTANT: This will save files A-L, do not interrupt and DO NOT DELETE THESE!
8. Once those files have been saved, they will appear on the TI Connect CE in your files tab.
9. Take those files, export them to your desktop and add them to a folder (this is for simplify sake)
10. Go back to your "ROM set up wizard" and now click on the "Browse for ROM" option.
11. Go find the folder you are using, select all parts of A-L and then send it to the wizard.
12. Once you do this, it should immediately send you back top the emulator and boot up the calculator.
13. When the calculator starts, there will only be a white opening page, so click enter to send you to the regular screen.
14. Use the KeyPad option on the bottom right side of the emulator to use the general functions of the calculator.
15. Use the same commands as if you are running the application: 2nd - 0 to open up the catalog, use the Asm function and then select program "prgm" and click on your BLOCKS.
16. This will launch the game as if it was on your calculator. 
17. Select your world and congrats! You should be able to see your saved world!

**NOTES:**
I would not make changes to the world as otherwise you would have to port it back to the calculator which I have NO idea how to do that.
If you try to take a video format, it will make a com piled PNG of hundreds of photos. A single PNG is fine but for a video you will need to insert all the photos into a stop motion software in order to get clean footage of what you are recording. 
Overall, this is a great way to view your world and interact with it through a simulator while also getting the footage you might want!

**HOPE THIS HELPS!**

**Comment by commandz0** [comment]
> I would not make changes to the world as otherwise you would have to port it back to the calculator which I have NO idea how to do that.

You can save appvars on the emulated calculator to 8xv files using the "calculator receive" pane - click the "view calculator variables" button, then select the appvars you're interested in, then hit the "save selected" button.

> If you try to take a video format, it will make a com piled PNG of hundreds of photos. A single PNG is fine but for a video you will need to insert all the photos into a stop motion software in order to get clean footage of what you are recording.

CEmu records animations as a single file in the APNG format, which is widely supported by browsers but not as often by video editors. You can use ffmpeg to convert it, or there are several websites that can do the conversion.

**Comment by Axylotl** [comment]
I had trouble with FFMPEG so I used [this](https://ezgif.com/apng-to-mp4) instead which worked great. 

https://ezgif.com/apng-to-mp4

I am going to set up a discord because I wish it existed when I was looking for answers to my questions.

**Comment by Gmrocks125** [comment]
@Axylotl Thank you for taking out time to write about this ... I will check it out

**Comment by Bee4Queer** [comment]
> @Axylotl Thank you for taking out time to write about this ... I will check it out

Did it work? If so, please close the issue.
